// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBxd7X_y5ZThkb4XME7yTGZxy-kCVUtwg',
    appId: '1:251901305410:web:25520b9bd71003842043db',
    messagingSenderId: '251901305410',
    projectId: 'beeman-d2037',
    authDomain: 'beeman-d2037.firebaseapp.com',
    storageBucket: 'beeman-d2037.firebasestorage.app',
    measurementId: 'G-RV1YCXWRH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp68Wlekm-1uirdPltolX7FUhJR5bMIRY',
    appId: '1:251901305410:android:06391a5d255645332043db',
    messagingSenderId: '251901305410',
    projectId: 'beeman-d2037',
    storageBucket: 'beeman-d2037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA11VEfbuJ6gAanhVSXhbJ9qVlRV8J-yvw',
    appId: '1:251901305410:ios:93340b4c4749ef9b2043db',
    messagingSenderId: '251901305410',
    projectId: 'beeman-d2037',
    storageBucket: 'beeman-d2037.firebasestorage.app',
    iosClientId: '251901305410-rk0lsnmjfk41nv1352ckjr6ulecfu2kv.apps.googleusercontent.com',
    iosBundleId: 'com.beeman.beeman',
  );

}