// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw09wDJw0MjEFJqyIxSRr-A433hpn7whg',
    appId: '1:143517254254:web:a992358545576dcb37dc7f',
    messagingSenderId: '143517254254',
    projectId: 'beeman-771bb',
    authDomain: 'beeman-771bb.firebaseapp.com',
    storageBucket: 'beeman-771bb.firebasestorage.app',
    measurementId: 'G-7MT9PC4Q6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgcjX2XuwIzkeQguZBefksFLvLobtdWn4',
    appId: '1:143517254254:android:00d8abbe0abe23f937dc7f',
    messagingSenderId: '143517254254',
    projectId: 'beeman-771bb',
    storageBucket: 'beeman-771bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUeI4AAhIIPWneF7MDm2BTY-Qb7lBnCHU',
    appId: '1:143517254254:ios:711981546e00e80437dc7f',
    messagingSenderId: '143517254254',
    projectId: 'beeman-771bb',
    storageBucket: 'beeman-771bb.firebasestorage.app',
    iosClientId: '143517254254-988nht2231j7jiqqnjadbf5ji7r3bmif.apps.googleusercontent.com',
    iosBundleId: 'com.beeman.beeman',
  );
}
