// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKjR49l43l0BwzPzQL6s2OXIlli-rxVxc',
    appId: '1:235985971391:web:cd469c44a45a7ec7943e0a',
    messagingSenderId: '235985971391',
    projectId: 'fir-beeman',
    authDomain: 'fir-beeman.firebaseapp.com',
    storageBucket: 'fir-beeman.firebasestorage.app',
    measurementId: 'G-TZV2KK57G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTchFlspHy7SVQOGPCJdFtSU2c0GX40lg',
    appId: '1:235985971391:android:f0e56b062ac77561943e0a',
    messagingSenderId: '235985971391',
    projectId: 'fir-beeman',
    storageBucket: 'fir-beeman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZNBVaENsMCHpHEb-JX7dOK9MtIChbN1c',
    appId: '1:235985971391:ios:e060afb503899c0d943e0a',
    messagingSenderId: '235985971391',
    projectId: 'fir-beeman',
    storageBucket: 'fir-beeman.firebasestorage.app',
    iosClientId: '235985971391-pdju8vkl1271tt0khr30dlg1str1nbqa.apps.googleusercontent.com',
    iosBundleId: 'com.beeman.beeman',
  );

}